global g_noises = {
  pickNoise: {
    threshold: 0,
    volume: 1,
    probability: 1,
    delay: 0,
    humanize: 0.1,
  },
  weakBuzz: {
    threshold: -20,
    volume: 0.5,
    probability: 0.2,
    delay: 25,
    humanize: 0.8,
  },
  pickBuzz: {
    threshold: 64,
    volume: 1,
    probability: 1,
    delay: 0,
    humanize: 0,
  },
  glideDown: {
    threshold: 0,
    probability: 0,
    volume: 0.75,
    delay: 0,
    humanize: 0,
  },
  pickStop: {
    threshold: 0,
    probability: 0,
    volume: 0.75,
    delay: 0,
    humanize: 0,
  },
  fretNoise: {
    threshold: 0,
    probability: 0,
    volume: 0.9,
    delay: 0,
    humanize: 0.4,
  },
  positionChange: {
    threshold: 0,
    probability: 1,
    volume: 0.9,
    delay: 0,
    humanize: 0.2,
  },
  fingerRelease: {
    threshold: 0,
    probability: 0,
    volume: 0.9,
    delay: 0,
    humanize: 0,
  },
  openString: {
    threshold: 0,
    probability: 0,
    volume: 0.75,
    delay: 0,
    humanize: 0,
  }
};
