global g_rr = {
  sustain: 1,
  muted: 1,
  chord: 5,
  vibrato: 1,
  harmonic: 2,
  pickNoise: 5,
  pickBuzz: 5,
  pickStop: 2,
  fretNoise: 2,
  fingerRelease: 2,
  glideDown: 1,
  strumNoise: 5,
  slowStrumNoise: 5,
  mutedStrumNoise: 12,
  bridgeMute: 5,
  positionChange: 5,
  palmHit: 5,
  fingerHit: 5,
  stringMuteBuzz: 5,
  pickguardHit: 12,
};
